### PR TITLE
feat: make tests independent of dcdunkan/tests

### PR DESCRIPTION
**Pull request by dcdunkan**

### CODE REVIEW

**Comment by rojvv** [comment]
What was dcdunkan/test’s problem again?

**Comment by dcdunkan** [comment]
> What was dcdunkan/test’s problem again?

Its a mess first of all. And it has issues with types and stuff, and I'm not able to fix them right now. Also tests are failing at #33 because of the library.

**Comment by rojvv** [comment]
Oh, alright. I just looked at the problem. I previously thought it could be fixed by importing grammY from lib.deno.dev, but looks like it’s not. So this PQ is fine.

**Comment by rojvv** [comment]
Remove the action too

**Comment by dcdunkan** [comment]
Why?

**Comment by rojvv** [comment]
I thought there was a dedicated action, sorry.

**Review by rojvv — APPROVED** [review]

**Pull request merged**
